version: '3'

services:
  app:
    build:
      context: .
    container_name: tasklist
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres?currentSchema=tasklist
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=oleg2004
    ports:
      - '8080:8080'
  db:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=oleg2004
      - POSTGRES_DB=tasklist
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d