spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=tasklist
    username: postgres
    password: oleg2004
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
security:
  jwt:
    secret: amF0amhvaWFob2loanE5ZXdqMDlyZWlvZmppZmppc2RqZnBkamZwb3Nkam9zZGZramZvcGpzZGY=
    access: 3600000
    refresh: 2592000000
