spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=tasklist
    username: postgres
    password: oleg2004
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist
  mail:
    host: smtp.gmail.com
    port: 587
    username: yfnf72@gmail.com
    password: bgsheojlsghifkpi
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
security:
  jwt:
    secret: amF0amhvaWFob2loanE5ZXdqMDlyZWlvZmppZmppc2RqZnBkamZwb3Nkam9zZGZramZvcGpzZGY=
    access: 3600000
    refresh: 2592000000
